name: Sync to Gitee

on:
  push:
    branches:
      - main  # 如果你的默認分支是 master，這裡請改成 master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: Yikun/gitee-mirror-action@master
        with:
          # 這裡換成你的 GitHub 用戶名/倉庫名
          src: shai102/media-renamer-ai
          # 這裡換成你的 Gitee 用戶名/倉庫名
          dst: gitee.com/shai102/media-renamer-ai
          dst_key: ${{ secrets.GITEE_SSH_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }} # 這是選填，如果沒配置 Token 可刪除此行
          static_list: "media-renamer-ai"
          force_update: true
          debug: true